---
env:
  node: true
  es6: true

extends:
  - airbnb-base

parserOptions:
  ecmaVersion: 2017
  sourceType: module

rules:
  import/no-extraneous-dependencies: ["error", { devDependencies: true }]
  class-methods-use-this: 0
  max-len: ["error", { code: 120 }]
  no-console: 0
